#############################################################################
# +-----------------------------------------------------------------------+ #
#
#     ██████╗██╗  ██╗ █████╗ ████████╗ ██████╗  █████╗ ████████╗███████╗
#    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝██╔════╝ ██╔══██╗╚══██╔══╝██╔════╝
#    ██║     ███████║███████║   ██║   ██║  ███╗███████║   ██║   █████╗
#    ██║     ██╔══██║██╔══██║   ██║   ██║   ██║██╔══██║   ██║   ██╔══╝
#    ╚██████╗██║  ██║██║  ██║   ██║   ╚██████╔╝██║  ██║   ██║   ███████╗
#    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝
#
# +-----------------------------------------------------------------------+ #
#############################################################################

version: 1.0.1
check-for-updates: true

chats:
  myfirstchat:
    format: "&a&lFIRST CHAT &8&l| &7%player% &8: &7%message%"
    display-name: "First Chat"
  myhexcoloredchat:
    format: "&#34dbeb&lHEX COLOR CHAT &8&l| &7%player% &8: &7%message%"
    display-name: "Hex Colored Chat"

messages:
  prefix: "&7[&dChatGate&7]"

  no-permission: "%prefix% &cYou don't have permission"
  chat-not-found: "%prefix% &cThe &f%chat% &cchat does not exist"
  unknown-subcommand: "%prefix% &cUnknown subcommand. Use /chatgate help"

  chat-enabled: "%prefix% &aYou have successfully enabled &f%chat% &achat"
  chat-disabled: "%prefix% &cYou have successfully disabled &f%chat% &cchat"

  config-reloaded: "%prefix% &aConfig reloaded successfully"

  none-chat-placeholder: "None"

settings:
  log-chat: true