name: ChatGate
version: '1.0'
main: it.AleCreeply.chatGate.ChatGate
api-version: '1.21'
author: 'AleCreeply'
softdepend: [PlaceholderAPI]
description: >
  ChatGate is a powerful and customizable chat manager plugin that allows server admins 
  to create multiple permission-based chat channels with support for HEX colors, 
  PlaceholderAPI, and toggleable chat modes. Easily configure chat formats, names, 
  permissions, and messages through the config.yml. 
  Perfect for roleplay servers, staff chats, VIP-only channels and more.
commands:
  chat:
    aliases: [c]
    description: To do
    usage: /chat <name> [message]
  chatgate:
    description: To do
    usage: /chatgate
    permission: chatgate.reload
    aliases:
      - cg
